binary_sensor:
  - platform: gpio
    pin:
      number: GPIO7
      mode:
        input: true
        pullup: true
    name: "Button 1"
    filters:
      - invert:
    on_multi_click:
      - timing:
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "1"
                action: "single_tap"
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "1"
                action: "double_tap"
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "1"
                action: "triple_tap"
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "1"
                action: "hold"

  - platform: gpio
    pin:
      number: GPIO8
      mode:
        input: true
        pullup: true
    name: "Button 2"
    filters:
      - invert:
    on_multi_click:
      - timing:
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "2"
                action: "single_tap"
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "2"
                action: "double_tap"
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "2"
                action: "triple_tap"
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "2"
                action: "hold"

  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
    name: "Button 3"
    filters:
      - invert:
    on_multi_click:
      - timing:
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "3"
                action: "single_tap"
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "3"
                action: "double_tap"
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "3"
                action: "triple_tap"
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.habuttonpad
              data:
                button: "3"
                action: "hold"
